### ISSUE TITLE
Dashboard doesn't report correct plot number and size

### ISSUE THREAD

**Issue by cpiga** [felixbrucker/chia-dashboard-satellite#104]
I installed chia satellite on a linux system. It worked fine but later I add on the chia-blockchain some plots folder and the dashboard doesn't report new plot in this folders. I checked the plots with "chia plots check" and the reported plot number and size is different from that reported in the dashboard.... I also tried to restart the satellite and to upgrade it. I didn't find chia satellite configuration file...
Plese help.
Bye 
Carlo

**Comment by Peacemak3r96** [comment]
Same Problem...

**Comment by felixbrucker** [comment]
If the issue still exists please feel free to reopen, closing here
