### ISSUE TITLE
update to Chia-Dashboard-Satellite 1.13 fail.

### ISSUE THREAD

**Issue by koy168hk** [felixbrucker/chia-dashboard-satellite#109]
Sir, i try use command to update the Chia-Dashboard-Satellite 1.13. I use npm install --global chia-dashboard-satellite and then being asked to use command npm install -g npm@8.4.1 to update it.

I got 8 computer, the strange things are: 5computer successful show that update to 1.13 successfully. However, another 3 computer fail, after the command many times, its still show the Chia-Dashboard-Satellite 1.12 only.

How can i solve this?  Should i remove all the Satellite in computer and reinstall it?  But i dun know how to do it. so asking for help, thx

**Comment by felixbrucker** [comment]
Can you please share the error message you get?

**Comment by koy168hk** [comment]
> Can you please share the error message you get?

Hi sir, i think its not an error message.
Just unable update to 1.13, i type same command on one of the computer,  but its only show 1.12.
So i would like to ask how can i update it to 1.13 if this command not work (npm install --global chia-dashboard-satellite)

**Comment by felixbrucker** [comment]
can you show the output of the update command?
