### ISSUE TITLE
monitoring a plotting machine

### ISSUE THREAD

**Issue by hijak** [felixbrucker/chia-dashboard-satellite#11]
Hi

i am faced with this error when trying to add a plotter (it is only doing plots) to the dashboard

```
2021-05-07 08:13:09.811 [ERROR] | Stats Collection | Error: connect ECONNREFUSED 127.0.0.1:55400
```
I can see this port is provided by the chia daemon. which service do i start to get that up? `node` ?

**Comment by felixbrucker** [comment]
Do you plot via the gui or cli? As of right now only gui plotting can provide stats, cli plotting does not expose any kind of api.

**Comment by hijak** [comment]
yes i plot via the cli. so i cant start any of the other services for it

**Comment by hijak** [comment]
ok thanks felix
