### ISSUE TITLE
Log in Chia dashboard 

### ISSUE THREAD

**Issue by lrsmining** [felixbrucker/chia-dashboard-satellite#113]
i cannot log in to chia dashboard ? Is there any issue ? 

Thank you

**Comment by felixbrucker** [comment]
Its working for me, can you provide any error messages, screenshots or some other more detailed error description?

**Comment by lrsmining** [comment]
If I go to https://chiadashboard.com/login and click continue with Github the site reload. Is there a new sign in process?

**Comment by felixbrucker** [comment]
I don't host this site, it is hosted by a community member

**Comment by lrsmining** [comment]
Can you send me an other login link ?

**Comment by felixbrucker** [comment]
https://dashboard.chia.foxypool.io is the one i host

**Comment by lrsmining** [comment]
thank you, who host the other one ?

**Comment by felixbrucker** [comment]
Giro, its linked at the bottom of the site

**Comment by lrsmining** [comment]
thank you
