### ISSUE TITLE
Changing API-Keys doesnt work

### ISSUE THREAD

**Issue by a1mless** [felixbrucker/chia-dashboard-satellite#12]
Hi,
I linked up the wrong google-account testing the dashboard but now i want to change it to another api-key.

Sadly just reinstalling via "npm uninstall -g chia-dashboard-satellite" doesnt delete the api key. 
So i went through your docs and found the config folder under "C:\Users\<User>\.config\chia-dashboard-satellite\config.yaml" i deleted it, reinstalled the dashboard once more and now it asked me for my api-key once again.
But when i enter i get the following error msg and the dashboard is all messed up:
![image](https://user-images.githubusercontent.com/7044983/117555938-eb3fa600-b063-11eb-9239-b352c4fb2175.png)

Any way to fix this?

**Comment by felixbrucker** [comment]
The stats retrieval is experiencing timeouts from your chia node (the chia node takes longer than 20 sec to respond). In my experience that usually happens with the wallet when also plotting via the gui. Does this apply to your node?

**Comment by a1mless** [comment]
Thanks for your response, yes I was plotting via gui. After rebooting the system the problem seems to be fixed, everything is showing up as its supposed to.
