### ISSUE TITLE
2021-05-09 16:22:19.303 [ERROR] | Dashboard Updater | Error: Request failed with status code 401

### ISSUE THREAD

**Issue by uniFiSense** [felixbrucker/chia-dashboard-satellite#13]
**Describe the bug**

2021-05-09 16:22:19.303 [ERROR] | Dashboard Updater | Error: Request failed with status code 401

**Comment by felixbrucker** [comment]
401 means your api key is invalid, maybe you deleted your satellite from the dashboard?

**Comment by agreenoff** [comment]
![image](https://user-images.githubusercontent.com/23742439/117581527-85751c00-b140-11eb-9f3c-5287aeb2cf95.png)

**Comment by agreenoff** [comment]
Before that I was using version 1.1.0

**Comment by uniFiSense** [comment]
> 401 means your api key is invalid, maybe you deleted your satellite from the dashboard?

Yes.
I created a new satellite on the dashboard and got a new api quay.
How do I insert a new api kei to a satellite program on my computer?

**Comment by felixbrucker** [comment]
Check out the docs here: https://docs.foxypool.io/chia-dashboard-satellite/configuration/

**Comment by uniFiSense** [comment]
Tnx.

Everything is OK now.
