### ISSUE TITLE
V1.13 / Windows - EU and US URLs don't recognize API keys for new dashboards

### ISSUE THREAD

**Issue by rkroelin** [felixbrucker/chia-dashboard-satellite#138]
**Describe the bug**
When trying this out for the first time I defaulted to https://us.chiadashboard.com.  I received the following error:

The api key for this satellite is invalid. Please use a valid api key!

I also tried the EU url with the same error.  However when I switched to https://chia-dashboard-api.foxypool.io it worked.  

**To Reproduce**

**Expected behavior**
Expected tool to recognize a new API key.

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Windows, binary version 1.13
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by thauch** [comment]
> **Describe the bug** When trying this out for the first time I defaulted to https://us.chiadashboard.com. I received the following error:
> 
> The api key for this satellite is invalid. Please use a valid api key!
> 
> I also tried the EU url with the same error. However when I switched to https://chia-dashboard-api.foxypool.io it worked.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen. Expected tool to recognize a new API key.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **System (please complete the following information):**
> 
> * OS: [e.g. Windows]
> * Windows, binary version 1.13
> * NodeJs Version [e.g. 10]
> 
> **Additional context** Add any other context about the problem here.

Which site did you create the api key from? foxypool or chiadashboard? They don't cross over. My guess you created the key on foxypool and tried to use it on chiadashboard.com.
