### ISSUE TITLE
the chia-dashboard-satellite cause an error to the Full Node 

### ISSUE THREAD

**Issue by bashar1988** [felixbrucker/chia-dashboard-satellite#14]
**Describe the bug**
i want to redo or uninstall the chia-dashboard-satellite can you help me please 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83901628/117589304-fad4f280-b128-11eb-8ce0-a0fd3a95d79b.png)
**System (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by felixbrucker** [comment]
> i want to redo or uninstall the chia-dashboard-satellite can you help me please

I'm not quite following on what you are trying to achive ulimately

To uninstall the satellite software you either just have to remove the exe if you "installed" it via running the exe, or when using npm you need to execute `npm uninstall --global chia-dashboard-satellite`
