### ISSUE TITLE
Capacity shows as "NaN"

### ISSUE THREAD

**Issue by electroboyz** [felixbrucker/chia-dashboard-satellite#148]
**Describe the bug**
Capacity shows as "NaN"

**To Reproduce**
Updated from 1.14 to 1.15 then got this error

**Expected behavior**
Should have shown real size

**Screenshots**

**System (please complete the following information):**
Windows 10, Ubuntu 22.04, Fedora 37, Rocky Linux

**Additional context**

**Comment by felixbrucker** [comment]
Hi there, the 1.15.0 update requires changes in the dashboard ui which it seems the forked community run dashboard did not yet add/merge: https://github.com/thauch/chia-dashboard-ui (last updated 2021)

The dashboard maintained by me is available here: https://dashboard.chia.foxypool.io/

**Comment by felixbrucker** [comment]
You can remove the config key or use `https://chia-dashboard-api.foxypool.io`

**Comment by felixbrucker** [comment]
Closing here, if the issue persists feel free to reopen
