### ISSUE TITLE
Feature Request: Return of image on Docker Hub

### ISSUE THREAD

**Issue by noisymime** [felixbrucker/chia-dashboard-satellite#150]
I know in the past that the Docker image for the satellite was published (https://hub.docker.com/r/felixbrucker/chia-dashboard-satellite) but at some point after 1.12 it was removed. 

It was very handy for keeping satellites managed and up to date and would be great to have it published once again, but I'm not sure if there were any specific reasons it was removed in the first place.

**Comment by felixbrucker** [comment]
Hi there, images are since available on githubs registry, because docker hub introduced stupid limitations, you can find the images here: https://github.com/felixbrucker/chia-dashboard-satellite/pkgs/container/chia-dashboard-satellite

**Comment by felixbrucker** [comment]
Closing here, if you have any question feel free to reopen 👍

**Comment by noisymime** [comment]
Thanks, I hadn't found those!
