### ISSUE TITLE
"Hide dismissed update notifications" option doesn't work on cellphone version of dashboard 

### ISSUE THREAD

**Issue by electroboyz** [felixbrucker/chia-dashboard-satellite#151]
**Describe the bug**
"Hide dismissed update notifications" option doesn't work on cellphone version of dashboard 

**To Reproduce**
Open the dashboard website on cellphone

**Expected behavior**
Update notification should have been eliminated from cellphone version of the dashboard too

**Screenshots**

**System (please complete the following information):**
iOS, Android

**Additional context**

**Comment by felixbrucker** [comment]
The option is per device and not synced across your account

**Comment by electroboyz** [comment]
i know. but on iphone where i put shortcut to the dashboard on its desktop the popups flooded every single time.

**Comment by felixbrucker** [comment]
![Screenshot_20230525-153251](https://github.com/felixbrucker/chia-dashboard-satellite/assets/5189997/1f278ac0-75b9-4302-b8d3-641af281d662)
![Screenshot_20230525-153256](https://github.com/felixbrucker/chia-dashboard-satellite/assets/5189997/9fb84067-da5b-4305-b8f0-889f752b3510)
![Screenshot_20230525-153302](https://github.com/felixbrucker/chia-dashboard-satellite/assets/5189997/c2f242fe-e208-40f1-9ec6-e8f3c8e9b751)

It's working fine here, you just need to close all banners once and click on the profile icon to get to the settings
