### ISSUE TITLE
excludedServices function doest work when inputting multiple variables

### ISSUE THREAD

**Issue by electroboyz** [felixbrucker/chia-dashboard-satellite#152]
**Describe the bug**

excludedServices doest work when inputting multiple variables. still showing both on dashboard

**To Reproduce**

excludedServices: farmer,harvester

or

excludedServices: 
  -farmer
  -harvester

**Expected behavior**

it should hide the variables inputted

**Screenshots**
doesnt need one

**System (please complete the following information):**
Windows 10, Ubuntu 22.04

**Additional context**

**Comment by felixbrucker** [comment]
Can you please try:
```yaml
excludedServices:
  - farmer
  - harvester
```
the spacing is important

You can also check the example here: https://docs.foxypool.io/proof-of-spacetime/chia-dashboard-satellite/configuration/#configuration-example

**Comment by electroboyz** [comment]
when I put this
_excludedServices:
  - farmer
  - harvester_

only the first line (farmer) got excluded

**Comment by felixbrucker** [comment]
Can you upload your config.yaml in here?

**Comment by felixbrucker** [comment]
Closing here
