### ISSUE TITLE
Disconnected harvester status is "Connected" in dashboard

### ISSUE THREAD

**Issue by salsaly4** [felixbrucker/chia-dashboard-satellite#2]
Maybe, after some timeout status of not connected/updated nodes should change to something like "Unknown" with the last available data?

Not is chows as "Connected" and is somehow misleading.

<img width="272" alt="Screenshot 2021-04-28 at 12 16 30" src="https://user-images.githubusercontent.com/16805161/116379876-1cc2a100-a81c-11eb-85d5-6b16256d05e6.png">

**Comment by felixbrucker** [comment]
Good point. i think i do this already with the summaries, makes sense to do it with the individual components as well 👍

**Comment by salsaly4** [comment]
Thanks!

**Comment by felixbrucker** [comment]
The change is now live 👍
