### ISSUE TITLE
Additional report for average access time during proof process

### ISSUE THREAD

**Issue by itongx** [felixbrucker/chia-dashboard-satellite#22]
In case of the size of farm getting big the access time is matter, so  I think is good to know an average access time to complete a puzzle and may able to manage the farm esp who is farm via NAS

**Comment by felixbrucker** [comment]
Sadly this info is not available via the chia api yet, the closest thing currently possible is to record the time it took harvesters to respond to signage points, but there is no info which harvester responded, so you cant match the results to a specific harvester in your network.

I'll look into recording the generic response times from all harvesters and maybe show avg/worst response times as a tsat for the farmer. Does this work for you?

**Comment by itongx** [comment]
yes I think it should wok

**Comment by felixbrucker** [comment]
I have added the avg and worst harvester response times (time from new signage point till a harvester responded) to the farmer sats card 👍

**Comment by 24601** [comment]
@felixbrucker - first, great work on the project in general, hope to learn how it works enough to help contribute, too. Second, can you elaborate on how you're calculating avg and worst harvester response times? I am seeing some outliers (on the high side) that do not seem realistic for my set up and the log file data all has sub-1s responses, yet I am setting "worst response" time being 14s+, and avg is way over what I'd calculate by hand looking at log files.

**Comment by felixbrucker** [comment]
The response time shown in the dashboard is the time it took from a new signage point announcement till the harvesters responded back to the farmer. The time you are referring to in the log is likely just the plot scan/lookup on disk, excluding the time till the harvester received the signage point and the time to respond the farming info back to the farmer.

The relevant line calculating this time is here: https://github.com/felixbrucker/chia-dashboard-satellite/blob/9ac0db0afe46416d7ad9f554d935fafbefde86c2/lib/service/stats-collection.js#L162

You can probbalky calculate these times yourself when search the farmer log for new signage points and checking when the responses for them come back in

**Comment by 24601** [comment]
> The response time shown in the dashboard is the time it took from a new signage point announcement till the harvesters responded back to the farmer. The time you are referring to in the log is likely just the plot scan/lookup on disk, excluding the time till the harvester received the signage point and the time to respond the farming info back to the farmer.
> 
> The relevant line calculating this time is here:
> 
> https://github.com/felixbrucker/chia-dashboard-satellite/blob/9ac0db0afe46416d7ad9f554d935fafbefde86c2/lib/service/stats-collection.js#L162
> 
> You can probbalky calculate these times yourself when search the farmer log for new signage points and checking when the responses for them come back in

Thank you so much @felixbrucker - I will do some manual checks, but, yes, I was looking at disk time. 

I appreciate it!
