### ISSUE TITLE
Monitoring of plotters triggered via CLI

### ISSUE THREAD

**Issue by kalosbg** [felixbrucker/chia-dashboard-satellite#23]
There are several plotter managers available. When plotting is triggered there the activity is not visible on the dashboard.
Will it be possible to add a monitoring of plotters that run in CLI?
Thanks!

**Comment by felixbrucker** [comment]
plots purely run via cli manually dont expose any kind of api, for plot managers you can request dashboard integration as a feature wit htheir respective developers 👍

**Comment by kalosbg** [comment]
Thank you for the prompt response!

**Comment by erdincsk** [comment]
please correct me if i am worng :)

o, chia-dashbord can only track plots which are created on gui and can not track any plots which are created by plot manager like plotman.

Is that right?

thanks a lot.
thanks btw for great jof :)

**Comment by felixbrucker** [comment]
yes, as of right now thats the gist

plotman (or other plot managers) could implement support for reporting stats to the dashboard tho

**Comment by kalosbg** [comment]
Felix, could you please share some API documentation?

Best regards, 
Kalin

**Comment by felixbrucker** [comment]
Yes, i'll post an update once it's available 👍

**Comment by kalosbg** [comment]
Thanks!

**Comment by felixbrucker** [comment]
I added some api docs regarding the authentication and updates of satellite stats here: https://docs.foxypool.io/chia-dashboard-satellite/api/

**Comment by kalosbg** [comment]
Hi Felix, 
It works really nice :) 
Thank you!

Now I'm thinking about even more features :)
It will be really useful to pass some details like  CPU, Memory, HDD usage, temperatures or even custom parameters ... and have them visible in the dashboard.

Thank you, 
Kalin

**Comment by kalosbg** [comment]
Felix,
Is it possible to turn off the plotting reporting of the original satellite
application because from time to time it overrides the reporting from my
CLI plotting script?

Best regards,
Kalin

**Comment by felixbrucker** [comment]
In the satellite config you can exclude the plotter service: https://docs.foxypool.io/chia-dashboard-satellite/configuration/#excludedservices
