### ISSUE TITLE
discrepancy between new Response Time feature and local metrics

### ISSUE THREAD

**Issue by sargonas** [felixbrucker/chia-dashboard-satellite#24]
Not sure if this issue is with the new update tracking Response Times, or if it's on my side so thought I would ask to see a bit more info. 

How is your Response Time collected and the average calculated? I'd like to know a bit more about that function, since after enabling it mine is astronomically high, yet I currently have Grafana and Prometheus running which are tracking the same thing, and showing my response times to average 0.6 seconds, while yours is telling me my average is 10-15 seconds. I'm trying to find out which source to put the most trust in, and if it is yours, then figure out how to get to the bottom of this previously unknown response delay.

(I do have spikes of 10-20 seconds for about an hour every 6 hours when I dump to disk from my plotting destination drives, but I wouldn't think they would push the full average that high, but maybe they do based on how you do your sampling?)

![image](https://user-images.githubusercontent.com/45463/118056614-1e718600-b33f-11eb-94c6-21a8eda682eb.png)

![image](https://user-images.githubusercontent.com/45463/118056641-27625780-b33f-11eb-8e43-40ad68cc088b.png)

![image](https://user-images.githubusercontent.com/45463/118056680-36e1a080-b33f-11eb-9bb4-211993715ee9.png)

**Comment by sargonas** [comment]
got what I needed from chatting in Discord.. long story short, two different kinds of metrics!

**Comment by thederpinator** [comment]
Could you elaborate on the longer version? I see this issue as well and rather not create a new one if it isn't an issue.
My harvester response times are <1s, but regularly reported higher in the dashboard.

**Comment by felixbrucker** [comment]
you can check if there was a chain re-org, in which case multiple/many challenges need to be handled by the farmer concurrently, slowing down the process til lthose are all processed

**Comment by sargonas** [comment]
To add to that, what  Felix explained to me in chat was that the log files are only calculating the return time locally for the harvester to check the plot. His metrics are counting the entire cycle from the moment the request comes in to the moment the check completes and resolves … Not just a harvester look up stage.
