### ISSUE TITLE
Request for ability to ignore a wallet - double counting wallets

### ISSUE THREAD

**Issue by wackywavytube** [felixbrucker/chia-dashboard-satellite#25]
I have 2 full nodes running and the tool looks at both wallets and counts them both. It would be nice if there was a way to ignore a duplicate wallet so it doesn't double count the amount of Chia I have.

**Comment by RagPoet** [comment]
Already possible - example here
https://docs.foxypool.io/chia-dashboard-satellite/configuration/

**Comment by felixbrucker** [comment]
As @RagPoet mentioned, already possible via config option, closing here
