### ISSUE TITLE
i'm error this console how to config 

### ISSUE THREAD

**Issue by konechiwa** [felixbrucker/chia-dashboard-satellite#27]
[ERROR] | Stats Collection | Error: Timeout of 20 seconds reached

this error for me how to config error tankyou

**Comment by felixbrucker** [comment]
Are you by any chance plotting via the gui on the machine experiencing this problem? Is you chia node updated to 1.1.5?

**Comment by Tototoua** [comment]
got the same error via plotting on gui, is it normal?

**Comment by felixbrucker** [comment]
Yes, its a known bug of chia-blockchain

**Comment by mySebbe** [comment]
What is the problem about higher the timeout?

**Comment by felixbrucker** [comment]
It doesn't solve the problem @mySebbe
