### ISSUE TITLE
Dashboard can't login

### ISSUE THREAD

**Issue by gbernardo** [felixbrucker/chia-dashboard-satellite#28]
I know this is the Satellite issues list, but I didn't see anywhere to report the dashboard is non-functional.  
Trying to authenticate with Google and it just keeps spinning (Authenticating..).

Status shows on the status page as yell (major outage) but does not show in "Past incidents".
![dashboard-fail](https://user-images.githubusercontent.com/8058556/118151833-af953b00-b3d9-11eb-8f10-394564c3aadb.png)

**Comment by Zero545** [comment]
I have the same problem and my satellite gives the following error message:

`chia-dashboard-satellite[820]: 2021-05-13 17:55:00.715 [ERROR] | Dashboard Updater | Error: Request failed with status code 429`

**Comment by sargonas** [comment]
Felix is currently troubleshooting an ongoing issue that is related to this. You can check the progress in Discord if you like, he's making minor updates in the Chia channel when available but presumably doesn't have time to respond to tickets about this at this time until the issue is resolved.

**Comment by Zero545** [comment]
Thank you for this information. It is also working again for me.

**Comment by felixbrucker** [comment]
The performance issues should now be resolved and you should be able to log in like usual

If you still experience issues feel free to reopen
