### ISSUE TITLE
ms/sec toggle

### ISSUE THREAD

**Issue by sargonas** [felixbrucker/chia-dashboard-satellite#29]
It would be nice if one could simply click on the aRT/wRT numbers to have them toggle between milliseconds format and seconds.

Ideally one's Average RT/Worst RT should be under a second in the few milliseconds range, but it isn't always. Generally speaking it's not hard for a person to move the decimal a few places over in ones head quickly to eyeball how many seconds it is, when it's over a second, and even then when 10 seconds or more one doesn't always need to know HOW many seconds it is, so much as just knowing it's over 10 and that's likely bad. Nonetheless, a simple click toggle on the number to alternate between formats would be convenient.

**Comment by felixbrucker** [comment]
Closed by https://github.com/felixbrucker/chia-dashboard-ui/commit/fa75c269c03a2dc9bf2f3386b15ce1618bf5dabf
