### ISSUE TITLE
Farmer Graphs issues

### ISSUE THREAD

**Issue by RagPoet** [felixbrucker/chia-dashboard-satellite#3]
**Describe the bug**
Plot passes graph lines drawn inconsistent

**To Reproduce**
Add satellite that is farming

**Expected behavior**
Smooth graph line that connects to the next point without skipping points that going back and connecting to past points

**Screenshots**
![image](https://user-images.githubusercontent.com/20522522/116472294-906baa80-a82a-11eb-8915-07210ca413ff.png)
![image](https://user-images.githubusercontent.com/20522522/116472811-3b7c6400-a82b-11eb-8cdd-c1280ab7146a.png)

**System (please complete the following information):**
 - OS: Windows 10 

**Additional context**
Satellite v1.1.1

**Comment by felixbrucker** [comment]
This is due to slow farmers responding late to challenges, sorting by last modfied date would "fix" the display but hide the actual problem here: slow farmers

**Comment by RagPoet** [comment]
Understood and seems reasonable. I am okay with the sorting fix as the graph isn't intended to find slow farmers.  Up to you.  Love the dashboard.  Any chance of a config option to not monitor a service on a satellite install?  If you have 2 full nodes with the same wallet keys (different networks) the Wallet Summary is double the actual value.  Being able to turn one off would solve that issue.

**Comment by felixbrucker** [comment]
>  Any chance of a config option to not monitor a service on a satellite install?

Good idea, I'll add that 👍
