### ISSUE TITLE
How do I connect several harvesters?

### ISSUE THREAD

**Issue by dnavamosler** [felixbrucker/chia-dashboard-satellite#31]
I would like to see all the harvesters that I have connected to my node, but I can't find the info.

**Comment by felixbrucker** [comment]
You'll need to setup a satellite for each harvester and run the satellite software on each system running a harvester

**Comment by dnavamosler** [comment]
I understand, but the combine says connect ECONNREFUSED <> IPNODE <>

> Deberá configurar un satélite para cada cosechadora y ejecutar el software de satélite en cada sistema que ejecute una cosechadora

**Comment by felixbrucker** [comment]
Do you have the satellite running on the machine running the harvester? Please show the error output of the satellite

**Comment by dnavamosler** [comment]
![image](https://user-images.githubusercontent.com/45084779/118186676-ff8cf580-b40b-11eb-8003-a8655f4819fc.png)

**Comment by felixbrucker** [comment]
ok multiple things:
- you seem to be using the harvester port, not the daemon port, daemon default port is 55400
- Make sure when using the daemon port, the daemon is also exposed on that remote ip, because by default it listens only on localhost. Normally youd run the satellite on the host `25.13.237.33` itself and not overrite the daemon address in the satellite config

**Comment by dnavamosler** [comment]
> ok varias cosas:
> 
> * parece que está utilizando el puerto del recolector, no el puerto del demonio, el puerto predeterminado del demonio es 55400
> * Asegúrese de que cuando utilice el puerto del demonio, el demonio también esté expuesto en esa ip remota, porque de forma predeterminada solo escucha en localhost. Normalmente, ejecutará el satélite en el `25.13.237.33`propio host y no sobrescribirá la dirección del demonio en la configuración del satélite.
> * También asegúrese de que el certificado de demonio para el demonio remoto esté presente en su directorio de configuración. No se recomienda conectarse a un demonio verdaderamente remoto

I have modified the corresponding port ... but, how can I check that the node is listening? in fact both computers are on the same local network physically

**Comment by felixbrucker** [comment]
Please just run the satellite on the remote harvester itself, you'll have far less problems and the setup is by far easier
