### ISSUE TITLE
No Harvester Graph on Dashboard

### ISSUE THREAD

**Issue by ApfelBirneKreis** [felixbrucker/chia-dashboard-satellite#32]
Noob here.

how do you get the harvester graph to show up.

also have the timeout problem. Using it on Unraid in a docker container

**Comment by felixbrucker** [comment]
Harvesters do not have a graph in the dashboard ui. Do you see any errors in the satellite output? Are you using the GUI chia node? What's your config like (excl api key)? Can you also post the output of the satellite? I need a little more info

**Comment by ApfelBirneKreis** [comment]
i had the timeout error but i think that got fixed with 1.6. The output shows
![image](https://user-images.githubusercontent.com/84158946/118307247-b5c70c80-b4ea-11eb-944c-4e621c387049.png)
![image](https://user-images.githubusercontent.com/84158946/118307319-d1caae00-b4ea-11eb-998f-e7f04898b141.png)
config is just the ordinary config

**Comment by felixbrucker** [comment]
Those errors are from when the dashboard api was under maintenance.

Oh you mean the farmer graph, not the harvester graph (bc there is no harvester graph)

> Are you using the GUI chia node? 
?

Also try a restart of the chia node in question

**Comment by ApfelBirneKreis** [comment]
no unfortunately for unraid there is only a no gui chia node. thing is a friend has it with the exact same configuration.
already did restart it a bunch of times. nothing changes.

**Comment by felixbrucker** [comment]
which command do you use to start the node?

**Comment by ApfelBirneKreis** [comment]
chia start farmer

**Comment by ApfelBirneKreis** [comment]
that should start the harvester, farmer, node and Bode

**Comment by felixbrucker** [comment]
yes, did you check the debug logs of chia for any errors?

**Comment by ApfelBirneKreis** [comment]
yes that was the first i did. No error there

**Comment by felixbrucker** [comment]
If the issue still persists feel free to reopen, closing here
