### ISSUE TITLE
[ERROR] | Dashboard Updater | The api key for this satellite is invalid. Please use a valid api key!

### ISSUE THREAD

**Issue by Manintorn** [felixbrucker/chia-dashboard-satellite#33]
Quick question for Mac User problem

I've deleted the satellite on website and want to reinstall it again.

The error shown below. how to fix it

![ภาพหน้าจอ 2564-05-14 เวลา 07 39 17](https://user-images.githubusercontent.com/84113906/118204095-abbff200-b487-11eb-8a35-33fc9e442c53.png)

**Comment by felixbrucker** [comment]
Check out the docs, you'll want to edit the satellite config and update the api key in there

**Comment by Manintorn** [comment]
> Check out the docs, you'll want to edit the satellite config and update the api key in there

Where is the docs? I cound't find it.

**Comment by felixbrucker** [comment]
![Screenshot_20210514-071909](https://user-images.githubusercontent.com/5189997/118225114-b9c04380-b484-11eb-98d5-867518e9da69.jpg)

**Comment by Manintorn** [comment]
![Uploading ภาพถ่ายหน้าจอ 2564-05-14 เวลา 12.30.40.png…]()

**Comment by felixbrucker** [comment]
This ain't the docs

**Comment by Manintorn** [comment]
> This ain't the docs

You said "Check out the docs" 

So, I click to the docs https://docs.foxypool.io/chia-dashboard-satellite/

Could you please specific where to go?

Thanks

**Comment by Manintorn** [comment]
![ภาพถ่ายหน้าจอ 2564-05-14 เวลา 12 52 35](https://user-images.githubusercontent.com/84113906/118227768-4c77d700-b4b3-11eb-8ef9-ded6c8493508.png)

I could not find the directory in "Mac"

You have any idea where it is?

**Comment by felixbrucker** [comment]
In your home directory, then navigate to the path mentioned in the docs in your screen
