### ISSUE TITLE
Update broke website

### ISSUE THREAD

**Issue by chiaproblem** [felixbrucker/chia-dashboard-satellite#36]
Update started throwing errors. Then, when I switched tabs the computer was missing. When I tried to add it back, I couldn't generate a new key. When I logged out, I can't log back in.

**Comment by chiaproblem** [comment]
Update: Can login but now getting error Request failed with status code 403 on .exe file with version 1.6

**Comment by thundervortex** [comment]
Similar 403 issue here... 1.5 Was working, updated to 1.6, now getting 403 error and cannot reconnect.  Tried reverting to 1.5 and same issue.  Even with a restart.

**Comment by dnavamosler** [comment]
![image](https://user-images.githubusercontent.com/45084779/118278186-b6828300-b497-11eb-88de-dc53d8733e57.png)

same problem here

**Comment by patryk-raba** [comment]
Same issue

**Comment by thauch** [comment]
Same

**Comment by lujadeph** [comment]
Same

**Comment by INSASY777** [comment]
Yep Error 403

**Comment by thundervortex** [comment]
> Similar 403 issue here... 1.5 Was working, updated to 1.6, now getting 403 error and cannot reconnect. Tried reverting to 1.5 and same issue. Even with a restart.

Also attempted a new API key and fresh Sattelite install.  Same 403 error.

**Comment by earthcryptominer** [comment]
> Same
> ![image](https://user-images.githubusercontent.com/7277391/118279917-47a22b80-b491-11eb-9211-13b1aef6e348.png)

Same issue here as well after updating

**Comment by luis-gmonkey** [comment]
It's seems that the API is under maintenance

https://foxypool.statuspage.io/

**Comment by felixbrucker** [comment]
The dashboard api was down for maintenance and upgrades, should be up again now 👍
