### ISSUE TITLE
2021-05-14 09:04:37.348 [ERROR] | Dashboard Updater | Error: Request failed with status code 403

### ISSUE THREAD

**Issue by billcod** [felixbrucker/chia-dashboard-satellite#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by billcod** [comment]
Terminal shows:"2021-05-14 09:04:37.348 [ERROR] | Dashboard Updater | Error: Request failed with status code 403"

**Comment by felixbrucker** [comment]
The dashboard api was down for maintenance and upgrades
