### ISSUE TITLE
Custom data passed via the API

### ISSUE THREAD

**Issue by kalosbg** [felixbrucker/chia-dashboard-satellite#40]
Hello,

In addition to the provided API it would be really useful if we can pass some custom data like system metrics: CPU, MEM, temperatures and others 
Maybe the data can be shown after hovering over the status of the plotter in a bubble or else.

Kind regards, 
Kalin

**Comment by gbernardo** [comment]
I was thinking the same thing.  Maybe available HDD space with a warning at a user defined threshold.

**Comment by felixbrucker** [comment]
@kalosbg are you integrating the api into any plot manager, or just private scripts?

**Comment by kalosbg** [comment]
@felixbrucker 
I integrated the API into "Swar-Chia-Plot-Manager" but because I'm not a programmer I did it how I can :)

I have https://openhardwaremonitor.org/ installed on the plotting machine to monitor some system metrics and was thinking if I can pass some data from there. Also "Swar-Chia-Plot-Manager" calculates the current plotting phase which will be useful if it is available in the dashboard.

**Comment by felixbrucker** [comment]
nice, got a github link or similar? might be able to show more stats when using swar compared to gui plotting (gui plotting stats kinda suck)

**Comment by kalosbg** [comment]
Yes, Swar manager provides really nice stats.
https://github.com/swar/Swar-Chia-Plot-Manager

I already started a discussion in the Swar's repo but still without responce.
https://github.com/swar/Swar-Chia-Plot-Manager/discussions/286

**Comment by kalosbg** [comment]
Hi @felixbrucker ,

A I can see a new column is available called "P", is this coming from phase?
Thanks!

**Comment by felixbrucker** [comment]
yes, check out the new additional fields: https://docs.foxypool.io/chia-dashboard-satellite/api/#the-satellite-service-stats-object

Btw there is a user in Discord who also implemented support in swar, maybe you both can get in touch given that there is a common goal:
![grafik](https://user-images.githubusercontent.com/5189997/118408428-e0010180-b685-11eb-8fcd-924b0f526fce.png)

**Comment by kalosbg** [comment]
Hi @felixbrucker,

Could you tell me where exactly you found the screenshot above?
Also please update the API documentation with the "Phase" parameter.

Kind regards, 
Kalin

**Comment by felixbrucker** [comment]
Hey @kalosbg 

the screen is from a discord user on the foxy discord, the current branch is here (i think): https://github.com/thauch/Swar-Chia-Plot-Manager/tree/chia-dashboard

The new (optional) fields are available in the full stats object reference here: https://docs.foxypool.io/chia-dashboard-satellite/api/#the-satellite-service-stats-object
