### ISSUE TITLE
Timeout of 20 seconds reached

### ISSUE THREAD

**Issue by ochompsky** [felixbrucker/chia-dashboard-satellite#42]
Dashboard was working fine yesterday but now no matter what I do, I get this: 

```
2021-05-14 17:01:10.979 [INFO] | Config loaded from /home/username/.config/chia-dashboard-satellite/config.yaml successfully
2021-05-14 17:01:40.077 [ERROR] | Stats Collection | Error: Timeout of 20 seconds reached
2021-05-14 17:02:00.079 [ERROR] | Stats Collection | Timeout of 20 seconds reached
```

Running on Ubuntu 20

**Comment by felixbrucker** [comment]
plotting via the gui currently results in this error because of a bug in chia-blockchain

**Comment by geimsdin** [comment]
I get the same plotting from Ubuntu server using CLI

**Comment by 750Four** [comment]
I'm having this too using Windows GUI, as a result Dashboard stats won't update. Is there any workaround?

**Comment by ochompsky** [comment]
are you on the latest version?  i still get the error in my console but my dash updates.

**Comment by 750Four** [comment]
So I just realized you have to constantly keep the Node.js command prompt open for the dashboard to update. I had no idea it worked this way. Dashboard is updating now. Timeout of 20 seconds error still persists though.

**Comment by mkdev-code** [comment]
same on 1.9 ver

**Comment by felixbrucker** [comment]
The 20 sec timeout is a clientside communication issue between satellite and chia node: chia node is not responding to api requests
