### ISSUE TITLE
After upgrading via npm always using old version

### ISSUE THREAD

**Issue by geimsdin** [felixbrucker/chia-dashboard-satellite#44]
Hi,
I'm plotting on an Ubuntu server 20.04, I did install chia-dashboard-satellite 1.5 using npm, I did upgrade to 1.6.2 and everything went fine but when I start it I get  that the version is still 1.5.0, also on dashboard website I still get the warning inviting me to upgrade. How should I solve this?

Thanks,

Simone

**Comment by mv-82** [comment]
Same problem here, same configuration (Ubuntu server 20.04).
After update 1.6.2 to 1.7.0, starting dashboard show "Chia-Dashboard-Satellite 1.6.2 initialized".

**Comment by felixbrucker** [comment]
Did you use nvm to install nodejs as your normal user?

**Comment by mv-82** [comment]
Nodejs installed with command "sudo apt -y install nodejs" after update repository to allow v12 install.
Also used sudo to install Chia-Dashboard-Satellite due to warning from npm "npm WARN checkPermission Missing write access to /usr/lib/node_modules/chia-dashboard-satellite"

**Comment by felixbrucker** [comment]
Using the system nodejs and runnign as root is not recommended, check out the docs on how to install nodejs on linux: https://docs.foxypool.io/general/installing-nodejs/

That beiong said, if you really want to use root and system nodejs youll also need to run all commands as root/sudo. You can verify the versions installed by checkout out the package.json in the storage location where the satellite is installed, probably in `/usr/lib/node_modules/chia-dashboard-satellite`

**Comment by mv-82** [comment]
Package.json in line 3 says:
"_id": "chia-dashboard-satellite@1.7.0"
and latest line says:
"version": "1.7.0"

**Comment by geimsdin** [comment]
I did install as sudo and updated as sudo, I cannot install a pkg as global without sudo privileges.

**Comment by felixbrucker** [comment]
I just tested this in a fresh ubuntu 20.04 installed, worked perfectly fine upgrading from 1.6.2 to 1.7.0 using root and system nodejs

Make sure you also start the satellite as root and do not have it instaleld anywhere else. When running the satellite and it is using an old version verify its binary path via `which chia-dashboard-satellite` and make sure it is what you'd expect

**Comment by ochompsky** [comment]
there is something really wrong with this package.  the update message would not go away so i i uninstalled it via npm uninstall -g, and it doesn't show up on npm -list.  

yet the binary is still there and it still runs.    try everything with both sudo and not sudo.  update doesn't work right, uninstall doesn't work right, nothing works right.

**Comment by felixbrucker** [comment]
Did you run `which chia-dashboard-satellite`? Please post the output of it

**Comment by geimsdin** [comment]
Uninstalled, reinstalled and cannot use it anymore.
Is there a way to uninstall it completely other than npm...?
I surely have still some file somewhere trying to read an old configuration now gone.

Simone

**Comment by felixbrucker** [comment]
when you run the npm uninstall command chia-dashboard-satellite is removed, the only thing left after that is the config file, if one was created

**Comment by erdie721** [comment]
I'm having this issue as well. Stuck on 1.6
which chia-dashboard-satellite returns /usr/local/bin/chia-dashboard-satellite and npm version 7.13.0

**Comment by felixbrucker** [comment]
> I'm having this issue as well. Stuck on 1.6
which chia-dashboard-satellite returns /usr/local/bin/chia-dashboard-satellite and npm version 7.13.0

Can you run the update/uninstall command as root?

does it still return that path after uninstalling, or the old version after updating with sudo?

**Comment by ochompsky** [comment]
> > I'm having this issue as well. Stuck on 1.6
> > which chia-dashboard-satellite returns /usr/local/bin/chia-dashboard-satellite and npm version 7.13.0
> 
> Can you run the update/uninstall command as root?
> 
> does it still return that path after uninstalling, or the old version after updating with sudo?

hey not the person you asked but i get that same output for `which chia-dashboard-satellite` even though i have run `npm uninstall chia-dashboard-satellite`  i've tried running that command both sudo as non sudo but the binary remains.  i think i need to blast away my entire npm/node and properly install as non-root.

**Comment by felixbrucker** [comment]
i think youl lwant to run the uninstall command with `--global` as well, same as on the install

**Comment by erdie721** [comment]
manually removed the chia-dashboard-satellite file from /usr/local/bin/ using sudo rm and it seems to be reading as the latest version now.

**Comment by ochompsky** [comment]
did the same and it's working
