### ISSUE TITLE
Stats Collection | Error: Request failed: {"error":"","success":false}

### ISSUE THREAD

**Issue by shiroamada** [felixbrucker/chia-dashboard-satellite#45]
**Describe the bug**
After I key in the API, key

```
(venv) shiro@chia:~/chia-blockchain$ chia-dashboard-satellite
2021-05-15 15:09:19.430 [INFO] | Config loaded from /home/shiro/.config/chia-dashboard-satellite/config.yaml successfully
2021-05-15 15:09:19.575 [ERROR] | Stats Collection | Error: Request failed: {"error":"","success":false}
2021-05-15 15:09:19.620 [INFO] | Chia-Dashboard-Satellite 1.7.0 initialized
2021-05-15 15:09:39.627 [ERROR] | Stats Collection | Error: Request failed: {"error":"","success":false}
2021-05-15 15:09:59.632 [ERROR] | Stats Collection | Error: Request failed: {"error":"","success":false}
.
.
.
```

**System (please complete the following information):**
 - OS: Ubuntu 20.04 (Virtual Machine)
 - NodeJs Version: 14.17

**Additional context**
I manage to see the info in dashboard web view.
![image](https://user-images.githubusercontent.com/2062946/118366464-e7b39e00-b5d2-11eb-8380-eb9180df66f9.png)

But Capacity is 0.00GB, is this something wrong?

**Comment by felixbrucker** [comment]
can you run `chia wallet show` and report back if there was a prompt (something about backups) and if that resulted in the error going away?

**Comment by shiroamada** [comment]
I am very new to chia, I was following this [setup instruction](https://david-waiting.medium.com/earn-chia-cryptocurrency-with-your-synology-nas-a-step-by-step-guide-fb3343ec6df2)

When I run `chia wallet show`, this is the output
```
No online backup file found, 
 Press S to skip restore from backup 
 Press F to use your own backup file:
```

When I run `chia show -cs`, I see got connections, I thought everything is working well.

![image](https://user-images.githubusercontent.com/2062946/118368459-bf2ca380-b5d4-11eb-8d5a-9c0baee834f9.png)

**Comment by felixbrucker** [comment]
Please press `s` in the prompt, this should fix the issue. The problem is that the wallet is currently not in an "initialized" state and api requests to it fail

**Comment by shiroamada** [comment]
Thanks!
