### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by stavrt** [felixbrucker/chia-dashboard-satellite#46]
Trying to login with google account and its throwing a 504 Gateway Timeout error
![image](https://user-images.githubusercontent.com/65147143/118386180-93fd8080-b5e3-11eb-87cd-b8d413a90f21.png)

**Comment by VerstandInvictus** [comment]
Same, and my satellites can't connect. If this is a maintenance, is there a way to post that in the web UI?

**Comment by felixbrucker** [comment]
Yes, please see: https://chiadashboard.statuspage.io/incidents/jylj830mk9l1 :sadge:

**Comment by VerstandInvictus** [comment]
Web UI now shows me a nice corner popup linking to that status page, thanks!

**Comment by felixbrucker** [comment]
VPS is up again 👍
