### ISSUE TITLE
Please how to install dashboard in ubuntu step by step

### ISSUE THREAD

**Issue by noeystyle** [felixbrucker/chia-dashboard-satellite#48]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by felixbrucker** [comment]
https://docs.foxypool.io/chia-dashboard-satellite/installing/

**Comment by billcod** [comment]
Felix,
  Thanks so much for your dashboard, which works great. Are you still going
to do Foxypool, or are you too busy now?
  Bill Crawford

**Comment by felixbrucker** [comment]
I plan to launch a foxy chia pool, yes
