### ISSUE TITLE
Extrem high response time

### ISSUE THREAD

**Issue by Romijoxx** [felixbrucker/chia-dashboard-satellite#49]
**Describe the bug**
I am having an extrem high response time

**To Reproduce**
Dont know but my Chia trys to solve old blocks.

**Expected behavior**
Solve new blocks and the RT should be around a few milliseconds

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17925930/118411445-ddf26f00-b694-11eb-95f1-d8a06d6ca4ba.png)

**System (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by felixbrucker** [comment]
The dashboard only shows stats, it can not improve slow farmers. Please check your logs.
