### ISSUE TITLE
Unable to authenticate on dashboard

### ISSUE THREAD

**Issue by gbernardo** [felixbrucker/chia-dashboard-satellite#52]
**Describe the bug**
I am trying to authenticate into the dashboard using Google or Github. Each time I get the spinning icon and then it times out to the login page.

**System (please complete the following information):**
 - OS: Windows 10 - Chrome.
 - OS: Windows 10 - FireFox.

**Additional context**
I cleared the cache on Chrome, then tried Firefox.

**Comment by gannon416** [comment]
same issue with discord and github.

**Comment by felixbrucker** [comment]
The dashboard hosted by foxy pool has had continuous VPS problems in the past days and as there does not seem to be an end to that it will be only available for existing foxy discord members to reduce the load. Other community members have started providing region based dashboards for everyone else, like https://eu.chiadashboard.com (possibly more will follow).

If desired the dashboard can also be self-hosted, as i open-sourced the core and ui, but this will probably be out of scope for most users.
