### ISSUE TITLE
why Harvester (p000) Status: Disconnected, but Full Node (p000) Status: Synced and Wallet (p000) Status: Synced?

### ISSUE THREAD

**Issue by ljboy1979** [felixbrucker/chia-dashboard-satellite#57]
why Harvester (p000) Status: Disconnected, but Full Node (p000) Status: Synced and Wallet (p000) Status: Synced?
![wal](https://user-images.githubusercontent.com/39668313/119016216-478fb780-b9cc-11eb-83ef-d339eadc9773.png)
![full](https://user-images.githubusercontent.com/39668313/119016239-4c546b80-b9cc-11eb-9ad6-ef663c4c4b80.png)
![far](https://user-images.githubusercontent.com/39668313/119016241-4ced0200-b9cc-11eb-8f88-093aa334b033.png)
![dis](https://user-images.githubusercontent.com/39668313/119016243-4d859880-b9cc-11eb-892d-51d80f2f434c.png)

**Comment by felixbrucker** [comment]
Please make sure no leftover/duplicate `start_xyz.exe` processes are running after shutting down the gui, then start the gui again
