### ISSUE TITLE
stats collection error

### ISSUE THREAD

**Issue by basunjoy3849** [felixbrucker/chia-dashboard-satellite#59]
![Capture](https://user-images.githubusercontent.com/83465336/119198285-b3465300-baa6-11eb-9a94-b4c889ced2b5.PNG)

Can anybody help me understand why i am getting this?

**Comment by felixbrucker** [comment]
This means your chia node is not responding to api requests. This is a known problem when using the chia gui to plot, which slows down the whole chia node.

**Comment by basunjoy3849** [comment]
Is there any way around this?
to solve this problem

**Comment by felixbrucker** [comment]
do not plot via the gui :D
