### ISSUE TITLE
Add support for multiple farms on a single account

### ISSUE THREAD

**Issue by Axadiw** [felixbrucker/chia-dashboard-satellite#6]
**Is your feature request related to a problem? Please describe.**
I have 3 separate "farms" with different accounts that I'm stroring rewards. I want to have separate stats for time needed to find a block, separate wallets etc. Currently I have to logout and log into different accounts in order to see all of them.

**Describe the solution you'd like**
It would be handy to have separate farms available from the single Gmail account

**Comment by felixbrucker** [comment]
With the dashboard sharing option you can open different dashboards in parallel without logging out 👍
