### ISSUE TITLE
Wallet is missing public key

### ISSUE THREAD

**Issue by Keeks18** [felixbrucker/chia-dashboard-satellite#60]
Since I did the update 1.9.1 on the Harvester, it always asks for the wallet public key. The dashboard also says Unknown.
How do I do that, that it is displayed to me on the dashboard?
![Unbenannt](https://user-images.githubusercontent.com/84678145/119269529-6e323600-bbf8-11eb-9ee1-4a40e253276d.PNG)

**Comment by Keeks18** [comment]
I entered this in the config and now it works fine on Harvester.
excludedServices:
  - wallet
  - fullNode

**Comment by felixbrucker** [comment]
Fixed with 1.9.2, wallets without keys will now not prevent satellite initialization
