### ISSUE TITLE
Farmer Summary, Harvester and wallet show unknown

### ISSUE THREAD

**Issue by choocl82** [felixbrucker/chia-dashboard-satellite#62]
any one know how to fix the issues, for Farmer Summary, Harvester and wallet show unknown state.

**Comment by felixbrucker** [comment]
You need to keep the satellite running

**Comment by choocl82** [comment]
> You need to keep the satellite running

Yes .. .the satellite was running ,  only Plotter and farmer was working . other show unknown.

**Comment by felixbrucker** [comment]
unknown is shown when there are no new stats for the service within a few minutes, make sure the satellite is running properly, as well as your chia services

**Comment by choocl82** [comment]
the problem is , when new configure it was work for all , after close for 2 days it show unknown.

**Comment by felixbrucker** [comment]
Sorry, im not following

**Comment by aliyucad** [comment]
I started having the same issue when I downloaded version 1.10.0. Before it was showing everything as they are supposed to be. How can I resolve this issue?

**Comment by aliyucad** [comment]
My OS is Ubuntu 20.04.

**Comment by felixbrucker** [comment]
If the issue still persists feel free to reopen, closing here
