### ISSUE TITLE
Config Linux Issue

### ISSUE THREAD

**Issue by gajebald** [felixbrucker/chia-dashboard-satellite#63]
Please select the dashboard url you want to use › https://chia-dashboard-api.foxypool.io
(node:20515) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFile' of undefined
    at Config.save (/usr/local/lib/node_modules/chia-dashboard-satellite/lib/service/config.js:48:14)
    at FirstRunWizard.run (/usr/local/lib/node_modules/chia-dashboard-satellite/lib/service/first-run-wizard.js:67:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:20515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:20515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by felixbrucker** [comment]
Please provide more info regarding your OS, node version etc so i can try to reproduce this
