### ISSUE TITLE
dashboard updater timeout

### ISSUE THREAD

**Issue by benqwu** [felixbrucker/chia-dashboard-satellite#66]
**Describe the bug**
I use Github account login the website failed, and everything was OK before today. 
![image](https://user-images.githubusercontent.com/38280874/120092627-ddeb7800-c146-11eb-9101-a82e2a327408.png)
![image](https://user-images.githubusercontent.com/38280874/120092615-c0b6a980-c146-11eb-9727-2316287987dc.png)

I find chia-dashboard-satellite-1.9.2-windows show that:
2021-05-30 12:51:03.839 [ERROR] | Dashboard Updater | Error: timeout of 15000ms exceeded
2021-05-30 12:51:18.816 [ERROR] | Dashboard Updater | Error: timeout of 15000ms exceeded
2021-05-30 12:51:34.606 [ERROR] | Dashboard Updater | Error: timeout of 15000ms exceeded

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by nzcool** [comment]
![image](https://user-images.githubusercontent.com/6011862/120093606-fdd26a00-c14d-11eb-847f-3e5c9144d8d1.png)

**Comment by felixbrucker** [comment]
Seems to be an issue with the eu/us hosted dashboards by third parties, not a bug in the satellite software

**Comment by benqwu** [comment]
> Seems to be an issue with the eu/us hosted dashboards by third parties, not a bug in the satellite software

Thank you. I will close this isssue.
