### ISSUE TITLE
can not login anymore on eu.chiadashboard.com

### ISSUE THREAD

**Issue by michaelklo** [felixbrucker/chia-dashboard-satellite#67]
Since tonight i can not login to eu.chiadashboard.com - Error 404 with Login failed: connect ECONNREFUSED 10.0.0.5:27017

i try login with my google account

Also on all Sattelites:

2021-05-30 11:00:38.650 [INFO] | Chia-Dashboard-Satellite 1.9.2 initialized
2021-05-30 11:00:53.617 [ERROR] | Dashboard Updater | Error: timeout of 15000ms exceeded
 
system is running without any troubles

Try to login now with GitHub Account - Same Problem
Try again with Discord - Same

**Comment by Henbal-Invest** [comment]
Same here - Update does not fix the issue

**Comment by michaelklo** [comment]
Still working now...
