### ISSUE TITLE
Add average response time from harvester

### ISSUE THREAD

**Issue by salsaly4** [felixbrucker/chia-dashboard-satellite#7]
Is it possible to add average (from several last signage points) response time for each harvester node? It's quite a vital metric, I think.

**Comment by felixbrucker** [comment]
I currently use the api available in each service, and sadly the response time isnt part of it: https://github.com/Chia-Network/chia-blockchain/blob/637177519aebb5de6303de40e56e8a5275245b99/chia/rpc/harvester_rpc_api.py#L14-L19

I might be able to add response times on the farmer side based on new farming infos, but i have no way of knowing which harvester they came from

**Comment by salsaly4** [comment]
I see, hope they'll get this info into harvester response )
