### ISSUE TITLE
Stuck after update

### ISSUE THREAD

**Issue by w4d3j** [felixbrucker/chia-dashboard-satellite#72]
I had a perfectly working configuration an hour ago.  I have done the following:

I moved primary farm from Windows to Manjaro (same machine).  Farmer works fine, everything's been trucking for weeks.  
I installed CDS following the official instructions.  I was able to add my new satellite to the web dashboard, where I saw a notification that said something about upgrading my harvester's satellite, so I turned to my other machine and did so.  When I turned back to my farmer, the CLI output is stuck at 
`w4d3@Rainbow-Sally:~$ chia-dashboard-satellite 
2021-06-03 13:52:43.839 [INFO] | Config loaded from /home/wade/.config/chia-dashboard-satellite/config.yaml successfully
2021-06-03 13:52:43.842 [INFO] | Using https://us.chiadashboard.com for stats submissions
2021-06-03 13:52:43.876 [INFO] | Chia-Dashboard-Satellite 1.10.0 initialized`
I looked back again and my harvester machine was stuck in the exact same spot, but this was an upgrade and not a fresh install.

If I followed the instructions exactly as written, things not just keep working?  Did I break something somehow by adding a second farmer satellite to my dashboard?  

Both machines are running latest Manjaro (KDE 5.21.5), linux-5.12, almost vanilla except for Chia stuff.

Please let me know if I have overlooked something.  

And thank you to the developers for manifesting good into the world.

**Comment by felixbrucker** [comment]
With "stuck" you mean what exactly? The satellite does only output errors after that initialized info log line

**Comment by w4d3j** [comment]
At first I thought the satellite CLI was stuck, but that was only because the dashboard isn't syncing:
![image](https://user-images.githubusercontent.com/4414148/120694213-eeb62980-c477-11eb-970c-4a03e74d0939.png)

It showed my harvester with a different, yellow-orange Unknown status for about 5 minutes before changing to the red Disconnected that is there now.

**Comment by felixbrucker** [comment]
That ui looks broken, it could be that this version of the dashboard ui was not updated yet

**Comment by w4d3j** [comment]
Thanks for switching the tags

I've force-refreshed the dashboard a few times, how long do you reckon it might take to proliferate?  Just so I don't sit here and keep hitting Ctrl+R  :upside_down_face:

**Comment by w4d3j** [comment]
Oops, my bad, I totally spaced on that.  You're not doing the web dashboard part at all!

I'll take my ~~bug~~ question to the appropriate place.  Thanks for pointing me in the right direction.
