### ISSUE TITLE
BitDefender detects Heur.BZC.YAX.Pantera.54.039BCA5F

### ISSUE THREAD

**Issue by jussipvainionpaa** [felixbrucker/chia-dashboard-satellite#76]
Today my Bitdefender Internet Security detected Heur.BZC.YAX.Pantera.54.039BCA5F in chia-dashboard-satellite.

I have no clue what that is but the path to the quarantined file is `C:\Users\user\AppData\Roaming\Microsoft\Windows\Recent\start chia dashboard satellite.js.lnk`

**Comment by felixbrucker** [comment]
The path you mentioned is a cache of recently accessed files by your user. The detection is a heuristic detection (HEUR), in this case (if you used the official binary or npm install) a false positive.

**Comment by jussipvainionpaa** [comment]
Ah alright. I figured it's just a false positive. I'm using the npm install.

I'll report this to BitDefender if they could make a note of it and maybe fix it.

**Comment by felixbrucker** [comment]
Thanks, appreciated 👍

**Comment by felixbrucker** [comment]
Closing here
