### ISSUE TITLE
Hi is it possible to use this dashboard for chia forks like spare, flax or greenchain ?

### ISSUE THREAD

**Issue by Namsoyo** [felixbrucker/chia-dashboard-satellite#78]
i would like to use this dashbord also for Forks of Chia. Would this be possible in future?

I tryed it with spare by changing the chia folder in yaml config File, but it didn't work.

**Comment by dnavamosler** [comment]
This would be great, I have tried to check the code but I did not find how to do it.

**Comment by bruelleerre** [comment]
This would be really nice. Maybe Felix or Namsoyo could check that, too.

**Comment by felixbrucker** [comment]
Some users forked the code to allow monitoring forks, but that is not planned for the upstream releases
