### ISSUE TITLE
i can't enter thje dashboard

### ISSUE THREAD

**Issue by dnavamosler** [felixbrucker/chia-dashboard-satellite#79]
**Describe the bug**
I cannot enter the dashboard, it does not allow me to login

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by w4d3j** [comment]
Can you provide any actual info about your setup or process?

**Comment by Ciuffospecial** [comment]
i have the same problem...i cannot login.
In the window there are two buttons:
![dashboard view](https://user-images.githubusercontent.com/75933849/147396871-ded21e63-4964-4cba-8e26-aafbda8e4380.PNG)
login
discord

clicking on login simply nothing happens
clicking on discord returns an error
![loginfail](https://user-images.githubusercontent.com/75933849/147396873-27577f0a-5670-464b-8850-8e8e646a5708.PNG)
